### ISSUE TITLE
Where to add filter in original ShopMagic plugin files?

### ISSUE THREAD

**Issue by kanoe92** [shopmagic/shopmagic-example#3]
Hello, I've got a problem where should I include code to add new placeholder filter in original ShopMagic plugin files and classes. I'm talking about this code:
`add_filter( 'shopmagic/core/placeholders', 'shopmagic_add_custom_placeholders' );`

I've studied this example, but I was wondering where it should be placed in original environment. Any help will be appreciated, thank you.

**Comment by bart-jaskulski** [comment]
Although the example may seem oversimplified, if you'd try to install it as a WordPress plugin, it would work correctly. You could actually base on this very piece of code, to create your own plugin.

Firstly, it's always the best to scope any code, which adds new functionalities to a separate plugin (multiple times I've made the mistake of putting advanced functionality into theme's code :wink:). And inside your plugin, it really depends on how you are used to registering hooks' callbacks. One advice, I'd give is to add the code after ShopMagic is fully loaded, to avoid too early calls to some classes:

```php
add_action(
  'shopmagic/core/initialized/v2',
  function ( \WPDesk\ShopMagic\Integration\ExternalPluginsAccess $sm ) {
     add_filter( 'shopmagic/core/placeholders', 'shopmagic_add_custom_placeholders' );
  }
);
```

Such snippet may safely land in the plugin's main file or any file which is loaded in your codebase. There's no strict rules.

You may want to look at [ShopMagic for Twilio's codebase](https://plugins.trac.wordpress.org/browser/shopmagic-for-twilio/trunk/src/Plugin.php) as an example of how our _production-level_ integration looks like. Mind, there's no adding filter with placeholders, etc. because it's been replaced with `Extension` class, but the rules stay the same.

**Comment by kanoe92** [comment]
Thank you, that really helped me. I've used github example plugin to create custom placeholders :)
